<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>bin\</BaseOutputPath>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.2.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OSP.Common.Domain">
      <HintPath>..\..\..\..\..\..\..\OCX\SPASv2\OSP\OSP.Common.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;C:\OCX\SPASv2&quot;&#xD;&#xA;xcopy &quot;$(OutDir)OSP.SPASv2.Domain.dll&quot; &quot;C:\OCX\SPASv2&quot; /Y /I" />
  </Target>

 


</Project>
